apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: apache-server # This tells the service to route traffic to our deployment pods
  ports:
    - protocol: TCP
      port: 80         # Internal cluster routing port
      targetPort: 80   # Port on the container to forward traffic to
      nodePort: 31080  # The specific port you will use on your Windows host machine
