apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Replace=true, Prune=false
  name: {{ include "my-app.fullname" . }}-chandednow
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: https
  selector:
    {{- include "my-app.selectorLabels" . | nindent 4 }}


